### ISSUE TITLE
Non signé

### ISSUE THREAD

**Issue by MatthieuLamp** [miyako/4d-plugin-zip#4]
Impossible d’ouvrir « Zip.bundle » car le développeur ne peut pas être vérifié.
Avec 4D v17 R5 sur macOS Catalina.

**Comment by miyako** [comment]
did you download the dmg from releases?
https://github.com/miyako/4d-plugin-zip/releases

**Comment by MatthieuLamp** [comment]
it's ok with the release ;-)
Thanks
