### ISSUE TITLE
Result code returned with unzip false

### ISSUE THREAD

**Issue by StanCT** [miyako/4d-plugin-zip#5]
Hello,

If i try to unzip a corrupted zip file (download interupted - file uncomplete), the result code returned is always 1.

Thanks

Have a good day

**Comment by miyako** [comment]
Quickly looking through the code, I see that the return value is set to 1 

* as soon as the file is opened 

and set to 0 when

* the command was aborted by the user (in callback method)

I suppose I could also be set to 0 when

* the command fails to get the number of entries
* the command fails to go to the first entry
* the command fails to go to the next entry and the total doesn't match the number of entries

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-zip/releases/tag/3.8.1

**Comment by StanCT** [comment]
Hello Keisuke,

Thank You very much for doing so quickly

Have a very nice day

Stanislas de Clermont-Tonnerre
L’UàG
129 rue de l’Abbé Groult
75015 Paris
_____________________ 
Tél 		 : +33 1 47 34 82 63
Mobile	 : +33 6 07 84 96 14
Mail 	  : sct@luag.fr <mailto:sct@luag.fr>
Web		 : http://www.luag.fr <http://www.luag.fr/>
_____________________
